name: 部署到 Server

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.repository_owner == 'MaaXYZ' && github.event.head_commit.author.email != '41898282+github-actions[bot]@users.noreply.github.com' }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 安装依赖
        run: pnpm install

      - name: 构建
        run: pnpm run build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          SOURCE: dist
          # ARGS: -avzr --delete
